### ISSUE TITLE
Dialog doesn't scroll vertically or handle large amounts of content

### ISSUE THREAD

**Issue by jfrankl** [raster-foundry/blasterjs#222] opened 2019-09-04 19:49 UTC
Not sure the best way to handle this, but right now when a dialog is taller than the viewport, it cannot be scrolled, which feels broken.

![image](https://user-images.githubusercontent.com/1809908/64286413-6796f300-cf2b-11e9-81e5-ea1bf9dc9aab.png)

**Comment by designmatty** [comment] 2019-09-04 20:00
Yeah, that's definitely not intended behavior. @lederer when you get the chance, take a look at this.

**Comment by designmatty** [comment] 2019-09-04 20:02
Oh actually, on second thought, this was fixed in a recent branch #215 but has yet to be released. @jfrankl if you test this on develop https://develop--raster-foundry-blaster.netlify.com/ it should work just fine.

**Closed as completed** 2019-09-04 20:18 UTC
